### ISSUE TITLE
Error Could not connect to debug target

### ISSUE THREAD

**Issue by Lereena** [microsoft/language-server-protocol#1120]
I'm trying to go through the lsp-sample with Language Server Extension Guide. 
I'm using the `Launch Client` configuration to debug:
```json
{
			"type": "extensionHost",
			"request": "launch",
			"name": "Launch Client",
			"runtimeExecutable": "${execPath}",
			"args": [
				"--extensionDevelopmentPath=${workspaceRoot}"
			],
			"outFiles": [
				"${workspaceRoot}/client/out/**/*.js"
			],
			"preLaunchTask": {
				"type": "npm",
				"script": "watch"
			}
		}
```
and getting
```
Visual Studio Code Error processing attach : Error Could not connect to debug target at http://localhost:6009: Promise was canceled
at e (/opt/visual-studio-code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:15:2455839)	
at async t (/opt/visual-studio-code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:46107)	
at async w.launch (/opt/visual-studio-code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:15:2477534)	
at async t.Binder.captureLaunch (/opt/visual-studio-code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:115411)	
at async t.Binder._launch (/opt/visual-studio-code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:114962)	
at async Promise.all (index 5)	at async t.Binder._boot (/opt/visual-studio-code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:114222)	at async t.default._onMessage (/opt/visual-studio-code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:15:2463780) 
``` 
error.
Changing the port on which the server should be running did not result in success.
What could be the reason for this behavior?

I'm using Manjaro Linux, Node.js 14.12.0 and VS Code 1.50.1.

**Comment by Razzeee** [comment]
Did your server start? The client has a rule for when it starts.
https://github.com/microsoft/vscode-extension-samples/blob/master/lsp-sample/package.json#L20

This means, that you need to open such a file in vscode first. Then connect to your server.

**Comment by Lereena** [comment]
@Razzeee This actually solved the problem, thanks for the help!
